// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package schema

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_UNACTIVATED Status = 0
	Status_ACTIVATED   Status = 1
	Status_DEACTIVATED Status = 2
)

var Status_name = map[int32]string{
	0: "UNACTIVATED",
	1: "ACTIVATED",
	2: "DEACTIVATED",
}

var Status_value = map[string]int32{
	"UNACTIVATED": 0,
	"ACTIVATED":   1,
	"DEACTIVATED": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type Field_Type int32

const (
	Field_STRING  Field_Type = 0
	Field_NUMBER  Field_Type = 1
	Field_BOOLEAN Field_Type = 2
	Field_EMAIL   Field_Type = 3
	Field_DATE    Field_Type = 4
	Field_TIME    Field_Type = 5
	Field_COLOR   Field_Type = 6
)

var Field_Type_name = map[int32]string{
	0: "STRING",
	1: "NUMBER",
	2: "BOOLEAN",
	3: "EMAIL",
	4: "DATE",
	5: "TIME",
	6: "COLOR",
}

var Field_Type_value = map[string]int32{
	"STRING":  0,
	"NUMBER":  1,
	"BOOLEAN": 2,
	"EMAIL":   3,
	"DATE":    4,
	"TIME":    5,
	"COLOR":   6,
}

func (x Field_Type) String() string {
	return proto.EnumName(Field_Type_name, int32(x))
}

func (Field_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1, 0}
}

type File_Type int32

const (
	File_SINGLE File_Type = 0
	File_LIST   File_Type = 1
)

var File_Type_name = map[int32]string{
	0: "SINGLE",
	1: "LIST",
}

var File_Type_value = map[string]int32{
	"SINGLE": 0,
	"LIST":   1,
}

func (x File_Type) String() string {
	return proto.EnumName(File_Type_name, int32(x))
}

func (File_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2, 0}
}

type Options struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Status               Status   `protobuf:"varint,3,opt,name=status,proto3,enum=schema.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Options) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Options) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNACTIVATED
}

type Field struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 Field_Type `protobuf:"varint,2,opt,name=type,proto3,enum=schema.Field_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetType() Field_Type {
	if m != nil {
		return m.Type
	}
	return Field_STRING
}

type File struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 File_Type `protobuf:"varint,2,opt,name=type,proto3,enum=schema.File_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetType() File_Type {
	if m != nil {
		return m.Type
	}
	return File_SINGLE
}

func init() {
	proto.RegisterEnum("schema.Status", Status_name, Status_value)
	proto.RegisterEnum("schema.Field_Type", Field_Type_name, Field_Type_value)
	proto.RegisterEnum("schema.File_Type", File_Type_name, File_Type_value)
	proto.RegisterType((*Options)(nil), "schema.Options")
	proto.RegisterType((*Field)(nil), "schema.Field")
	proto.RegisterType((*File)(nil), "schema.File")
}

func init() {
	proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206)
}

var fileDescriptor_555bd8c177793206 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcd, 0x6a, 0xf2, 0x40,
	0x14, 0x75, 0x34, 0xc6, 0xcf, 0xeb, 0x57, 0x3b, 0xbd, 0xdd, 0x64, 0xd1, 0x85, 0x84, 0x56, 0xa4,
	0x8b, 0x2c, 0xec, 0xaa, 0xcb, 0x44, 0x47, 0x09, 0xc4, 0x44, 0xe2, 0xd8, 0xad, 0x58, 0x3b, 0x60,
	0xc0, 0x64, 0x82, 0x89, 0x05, 0x5f, 0xa5, 0x4f, 0x5b, 0x66, 0x54, 0x62, 0xc1, 0xdd, 0xf9, 0x61,
	0xce, 0x3d, 0xcc, 0x81, 0xff, 0x1b, 0x99, 0xa6, 0x32, 0x73, 0xf2, 0xbd, 0x2c, 0x25, 0x9a, 0xc5,
	0x66, 0x2b, 0xd2, 0xb5, 0xbd, 0x82, 0x56, 0x94, 0x97, 0x89, 0xcc, 0x0a, 0x44, 0x30, 0xb2, 0x75,
	0x2a, 0x2c, 0xd2, 0x23, 0x83, 0x76, 0xac, 0x31, 0x5a, 0xd0, 0xfa, 0x16, 0xfb, 0x22, 0x91, 0x99,
	0x55, 0xd7, 0xf2, 0x85, 0x62, 0x1f, 0xcc, 0xa2, 0x5c, 0x97, 0x87, 0xc2, 0x6a, 0xf4, 0xc8, 0xa0,
	0x3b, 0xec, 0x3a, 0xa7, 0x44, 0x67, 0xa1, 0xd5, 0xf8, 0xec, 0xda, 0x3f, 0x04, 0x9a, 0x93, 0x44,
	0xec, 0xbe, 0x6e, 0xe6, 0xf7, 0xc1, 0x28, 0x8f, 0xb9, 0xd0, 0xe1, 0xdd, 0x21, 0x5e, 0x32, 0xf4,
	0x03, 0x87, 0x1f, 0x73, 0x11, 0x6b, 0xdf, 0x5e, 0x82, 0xa1, 0x18, 0x02, 0x98, 0x0b, 0x1e, 0xfb,
	0xe1, 0x94, 0xd6, 0x14, 0x0e, 0x97, 0x33, 0x8f, 0xc5, 0x94, 0x60, 0x07, 0x5a, 0x5e, 0x14, 0x05,
	0xcc, 0x0d, 0x69, 0x1d, 0xdb, 0xd0, 0x64, 0x33, 0xd7, 0x0f, 0x68, 0x03, 0xff, 0x81, 0x31, 0x76,
	0x39, 0xa3, 0x86, 0x42, 0xdc, 0x9f, 0x31, 0xda, 0x54, 0xf6, 0x28, 0x0a, 0xa2, 0x98, 0x9a, 0xf6,
	0x0a, 0x8c, 0x49, 0xb2, 0x13, 0x37, 0xab, 0xbd, 0xfc, 0xa9, 0xf6, 0x50, 0x55, 0xdb, 0x89, 0xeb,
	0x66, 0x4f, 0x57, 0xcd, 0xfc, 0x70, 0x1a, 0x30, 0x5a, 0x53, 0xb7, 0x02, 0x7f, 0xc1, 0x29, 0x79,
	0x7d, 0x07, 0xf3, 0xf4, 0x1f, 0x78, 0x0f, 0x9d, 0x65, 0xe8, 0x8e, 0xb8, 0xff, 0xe1, 0x72, 0x36,
	0xa6, 0x35, 0xbc, 0x83, 0x76, 0x45, 0x89, 0xf2, 0xc7, 0xac, 0x12, 0xea, 0xde, 0x33, 0x3c, 0x6e,
	0x64, 0xea, 0xe4, 0xdb, 0xa4, 0x38, 0x24, 0xa5, 0x38, 0xdf, 0xf7, 0x3a, 0x23, 0x3d, 0xe3, 0x5c,
	0xad, 0x38, 0x27, 0x9f, 0xa6, 0x9e, 0xf3, 0xed, 0x37, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x06, 0xc8,
	0x48, 0xde, 0x01, 0x00, 0x00,
}
