// Code generated by protoc-gen-go. DO NOT EDIT.
// source: process.proto

package schema

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Process struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string           `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Status               Status           `protobuf:"varint,3,opt,name=status,proto3,enum=schema.Status" json:"status,omitempty"`
	Input                *Process_Payload `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Output               *Process_Payload `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	Error                *Event           `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_54c4d0e8c0aaf5c3, []int{0}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Process) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Process) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNACTIVATED
}

func (m *Process) GetInput() *Process_Payload {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Process) GetOutput() *Process_Payload {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *Process) GetError() *Event {
	if m != nil {
		return m.Error
	}
	return nil
}

type Process_Payload struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Entity               *Entity  `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Process_Payload) Reset()         { *m = Process_Payload{} }
func (m *Process_Payload) String() string { return proto.CompactTextString(m) }
func (*Process_Payload) ProtoMessage()    {}
func (*Process_Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_54c4d0e8c0aaf5c3, []int{0, 0}
}

func (m *Process_Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process_Payload.Unmarshal(m, b)
}
func (m *Process_Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process_Payload.Marshal(b, m, deterministic)
}
func (m *Process_Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process_Payload.Merge(m, src)
}
func (m *Process_Payload) XXX_Size() int {
	return xxx_messageInfo_Process_Payload.Size(m)
}
func (m *Process_Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Process_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Process_Payload proto.InternalMessageInfo

func (m *Process_Payload) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Process_Payload) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*Process)(nil), "schema.Process")
	proto.RegisterType((*Process_Payload)(nil), "schema.Process.Payload")
}

func init() {
	proto.RegisterFile("process.proto", fileDescriptor_54c4d0e8c0aaf5c3)
}

var fileDescriptor_54c4d0e8c0aaf5c3 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdd, 0x6a, 0xe3, 0x30,
	0x10, 0x85, 0x51, 0x7e, 0x1c, 0x76, 0xf2, 0x07, 0xda, 0x8b, 0x35, 0xbe, 0x0a, 0xbb, 0x6c, 0x1b,
	0x02, 0x75, 0x4b, 0xfa, 0x04, 0x4d, 0x1b, 0x4a, 0xa1, 0x50, 0xe3, 0xd2, 0xde, 0xab, 0xce, 0x40,
	0x04, 0xb5, 0x64, 0xa4, 0x71, 0x20, 0xef, 0xd6, 0x17, 0xea, 0x5b, 0x14, 0x4b, 0x32, 0x85, 0x10,
	0x4a, 0xae, 0xa4, 0x39, 0xe7, 0x93, 0x46, 0x47, 0x0c, 0x8c, 0x2b, 0xa3, 0x0b, 0xb4, 0x36, 0xad,
	0x8c, 0x26, 0xcd, 0x23, 0x5b, 0x6c, 0xb1, 0x14, 0xc9, 0xa8, 0xd0, 0x65, 0xa9, 0x95, 0x57, 0x93,
	0x21, 0xee, 0x50, 0x51, 0x28, 0x46, 0xa8, 0x48, 0xd2, 0xde, 0x57, 0x7f, 0x3f, 0x3a, 0x30, 0xc8,
	0xfc, 0x15, 0x9c, 0x43, 0x4f, 0x89, 0x12, 0x63, 0x36, 0x63, 0xf3, 0x5f, 0xb9, 0xdb, 0xf3, 0x18,
	0x06, 0x3b, 0x34, 0x56, 0x6a, 0x15, 0x77, 0x9c, 0xdc, 0x96, 0xfc, 0x0c, 0x22, 0x4b, 0x82, 0x6a,
	0x1b, 0x77, 0x67, 0x6c, 0x3e, 0x59, 0x4e, 0x52, 0xdf, 0x3b, 0x7d, 0x76, 0x6a, 0x1e, 0x5c, 0x7e,
	0x01, 0x7d, 0xa9, 0xaa, 0x9a, 0xe2, 0xde, 0x8c, 0xcd, 0x87, 0xcb, 0x3f, 0x2d, 0x16, 0xba, 0xa6,
	0x99, 0xd8, 0xbf, 0x6b, 0xb1, 0xc9, 0x3d, 0xc5, 0x2f, 0x21, 0xd2, 0x35, 0x35, 0x7c, 0xff, 0x67,
	0x3e, 0x60, 0xfc, 0x1f, 0xf4, 0xd1, 0x18, 0x6d, 0xe2, 0xc8, 0xf1, 0xe3, 0x96, 0x5f, 0x37, 0x99,
	0x73, 0xef, 0x25, 0xaf, 0x30, 0x08, 0xe7, 0x1c, 0xdf, 0x58, 0x2e, 0xe6, 0x11, 0xbe, 0x59, 0x9a,
	0x70, 0xfe, 0x9b, 0x5c, 0xea, 0xe1, 0x77, 0xb8, 0xb5, 0x53, 0xf3, 0xe0, 0x2e, 0x3f, 0x19, 0x40,
	0x78, 0xd8, 0x4d, 0xf6, 0xc0, 0x17, 0xd0, 0x7b, 0x94, 0x96, 0xf8, 0xb4, 0xc5, 0x9f, 0x2a, 0x92,
	0x5a, 0xd9, 0x64, 0x7a, 0x90, 0xe2, 0x8a, 0xf1, 0x73, 0xe8, 0xde, 0xe3, 0x09, 0x28, 0x5f, 0x40,
	0x74, 0x6b, 0x50, 0x10, 0xf2, 0x43, 0xeb, 0x28, 0xfb, 0x52, 0x6d, 0x4e, 0x63, 0x53, 0x80, 0x3b,
	0x14, 0x05, 0xc9, 0xdd, 0x49, 0xfc, 0xea, 0x3f, 0xfc, 0x2e, 0x74, 0x99, 0x56, 0x5b, 0x69, 0x6b,
	0x49, 0x18, 0xec, 0xd5, 0x28, 0xf8, 0x59, 0x33, 0x4f, 0x19, 0x7b, 0x8b, 0xdc, 0x60, 0x5d, 0x7f,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x70, 0x8d, 0xde, 0x9a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProcessAPIClient is the client API for ProcessAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProcessAPIClient interface {
	List(ctx context.Context, in *Options, opts ...grpc.CallOption) (ProcessAPI_ListClient, error)
	Get(ctx context.Context, in *Options, opts ...grpc.CallOption) (*Process, error)
	Create(ctx context.Context, in *Process, opts ...grpc.CallOption) (*Process, error)
	Update(ctx context.Context, in *Process, opts ...grpc.CallOption) (*Process, error)
	Deactivate(ctx context.Context, in *Process, opts ...grpc.CallOption) (*Process, error)
}

type processAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessAPIClient(cc grpc.ClientConnInterface) ProcessAPIClient {
	return &processAPIClient{cc}
}

func (c *processAPIClient) List(ctx context.Context, in *Options, opts ...grpc.CallOption) (ProcessAPI_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProcessAPI_serviceDesc.Streams[0], "/schema.ProcessAPI/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &processAPIListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProcessAPI_ListClient interface {
	Recv() (*Process, error)
	grpc.ClientStream
}

type processAPIListClient struct {
	grpc.ClientStream
}

func (x *processAPIListClient) Recv() (*Process, error) {
	m := new(Process)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *processAPIClient) Get(ctx context.Context, in *Options, opts ...grpc.CallOption) (*Process, error) {
	out := new(Process)
	err := c.cc.Invoke(ctx, "/schema.ProcessAPI/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processAPIClient) Create(ctx context.Context, in *Process, opts ...grpc.CallOption) (*Process, error) {
	out := new(Process)
	err := c.cc.Invoke(ctx, "/schema.ProcessAPI/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processAPIClient) Update(ctx context.Context, in *Process, opts ...grpc.CallOption) (*Process, error) {
	out := new(Process)
	err := c.cc.Invoke(ctx, "/schema.ProcessAPI/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processAPIClient) Deactivate(ctx context.Context, in *Process, opts ...grpc.CallOption) (*Process, error) {
	out := new(Process)
	err := c.cc.Invoke(ctx, "/schema.ProcessAPI/Deactivate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessAPIServer is the server API for ProcessAPI service.
type ProcessAPIServer interface {
	List(*Options, ProcessAPI_ListServer) error
	Get(context.Context, *Options) (*Process, error)
	Create(context.Context, *Process) (*Process, error)
	Update(context.Context, *Process) (*Process, error)
	Deactivate(context.Context, *Process) (*Process, error)
}

// UnimplementedProcessAPIServer can be embedded to have forward compatible implementations.
type UnimplementedProcessAPIServer struct {
}

func (*UnimplementedProcessAPIServer) List(req *Options, srv ProcessAPI_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedProcessAPIServer) Get(ctx context.Context, req *Options) (*Process, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedProcessAPIServer) Create(ctx context.Context, req *Process) (*Process, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedProcessAPIServer) Update(ctx context.Context, req *Process) (*Process, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedProcessAPIServer) Deactivate(ctx context.Context, req *Process) (*Process, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deactivate not implemented")
}

func RegisterProcessAPIServer(s *grpc.Server, srv ProcessAPIServer) {
	s.RegisterService(&_ProcessAPI_serviceDesc, srv)
}

func _ProcessAPI_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Options)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessAPIServer).List(m, &processAPIListServer{stream})
}

type ProcessAPI_ListServer interface {
	Send(*Process) error
	grpc.ServerStream
}

type processAPIListServer struct {
	grpc.ServerStream
}

func (x *processAPIListServer) Send(m *Process) error {
	return x.ServerStream.SendMsg(m)
}

func _ProcessAPI_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Options)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessAPIServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.ProcessAPI/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessAPIServer).Get(ctx, req.(*Options))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessAPI_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Process)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessAPIServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.ProcessAPI/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessAPIServer).Create(ctx, req.(*Process))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessAPI_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Process)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessAPIServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.ProcessAPI/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessAPIServer).Update(ctx, req.(*Process))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessAPI_Deactivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Process)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessAPIServer).Deactivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.ProcessAPI/Deactivate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessAPIServer).Deactivate(ctx, req.(*Process))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProcessAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schema.ProcessAPI",
	HandlerType: (*ProcessAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ProcessAPI_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ProcessAPI_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProcessAPI_Update_Handler,
		},
		{
			MethodName: "Deactivate",
			Handler:    _ProcessAPI_Deactivate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _ProcessAPI_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "process.proto",
}
